
```{r}
library(tidyverse)
library(BerkeleyForestsAnalytics)
library(stringr)
options(scipen = 999)
```

```{r}
ca_tree <- read_csv("CA_TREE.csv") 
ca_cond <- read_csv("CA_COND.csv") 
ca_plotsnap <- read_csv("CA_PLOTSNAP.csv") 
```

```{r}
ca_cond_filter <- ca_cond %>%
  filter(INVYR == 2021) %>%
  mutate(STATECD = as.character(STATECD),
         UNITCD = as.character(UNITCD),
         COUNTYCD = as.character(COUNTYCD),
         PLOT = as.character(PLOT),
         INVYR = as.character(INVYR),
         CONDID = as.character(CONDID),
         stand_org = as.character(STDORGCD)) %>%
  select(STATECD, UNITCD, COUNTYCD, PLOT, INVYR, CONDID, stand_org)

head(ca_cond_filter)
```

```{r}
ca_plot_filter <- ca_plotsnap %>%
  mutate(STATECD = as.character(STATECD),
         UNITCD = as.character(UNITCD),
         COUNTYCD = as.character(COUNTYCD),
         PLOT = as.character(PLOT),
         INVYR = as.integer(INVYR)) %>%
  group_by(STATECD, UNITCD, COUNTYCD, PLOT) %>%
  slice_max(INVYR, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(province = str_extract(ECOSUBCD, "^[A-Za-z]?\\d{3}"),
         letter = str_extract(province, "^[A-Za-z]"),
         number = as.numeric(str_extract(province, "\\d{3}")),
         rounded_number = floor(number/10)*10,
         division = paste0(coalesce(letter, ""), rounded_number)) %>%
  select(STATECD, UNITCD, COUNTYCD, PLOT, division, province)

head(ca_plot_filter)
```

```{r}
ca_tree_filter <- ca_tree %>%
  filter(INVYR == 2021,
         STATUSCD == 1 | STATUSCD == 2) %>%
  mutate(STATECD = as.character(STATECD),
         UNITCD = as.character(UNITCD),
         COUNTYCD = as.character(COUNTYCD),
         PLOT = as.character(PLOT),
         INVYR = as.character(INVYR),
         CONDID = as.character(CONDID),
         site = as.character(STATECD),
         plot = as.character(PLOT),
         exp_factor = 50,
         status = as.character(STATUSCD),
         decay_class = as.character(DECAYCD),
         species = as.character(SPCD),
         dbh = DIA,
         ht1 = HT,
         ht2 = ACTUALHT,
         crown_ratio = CR/100,
         top = if_else(HT > ACTUALHT, "N", "Y"),
         cull = CULL,
         total_wood_fia = DRYBIO_STEM*0.45359, # for tons use 0.0005
         total_bark_fia = DRYBIO_STEM_BARK*0.45359,
         total_branch_fia = DRYBIO_BRANCH*0.45359,
         merch_wood_fia = DRYBIO_BOLE*0.45359,
         merch_bark_fia = DRYBIO_BOLE_BARK*0.45359,
         stump_wood_fia = DRYBIO_STUMP*0.45359,
         stump_bark_fia = DRYBIO_STUMP_BARK*0.45359,
         foliage_fia = DRYBIO_FOLIAGE*0.45359) %>%
  select(STATECD, UNITCD, COUNTYCD, PLOT, INVYR, CONDID,
         site, plot, exp_factor, status, decay_class, species, 
         dbh, ht1, ht2, crown_ratio, top, cull,
         total_wood_fia, total_bark_fia, total_branch_fia,
         merch_wood_fia, merch_bark_fia,
         stump_wood_fia, stump_bark_fia, foliage_fia) %>%
  drop_na(status, species, dbh, ht1, ht2, crown_ratio, total_wood_fia, total_bark_fia, total_branch_fia, foliage_fia) %>%
  filter(!(status == "2" & is.na(decay_class)))

head(ca_tree_filter)
dim(ca_tree_filter)
```

```{r}
ca_bfa_data <- left_join(ca_tree_filter, ca_cond_filter, by = c("STATECD","UNITCD","COUNTYCD","PLOT","INVYR","CONDID")) %>%
  mutate(stand_org = if_else(is.na(stand_org),"0","1")) %>%
  left_join(ca_plot_filter, by = c("STATECD","UNITCD","COUNTYCD","PLOT")) %>%
  select(-c(STATECD, UNITCD, COUNTYCD, PLOT, INVYR, CONDID)) %>%
  select(division, province, site, plot, stand_org, everything())

head(ca_bfa_data)
dim(ca_bfa_data)
```

```{r}
ca_check <- BiomassNSVB(data = ca_bfa_data,
                        results = "by_tree",
                        input_units = "imperial",
                        output_units = "metric")
```

```{r}
# use 1g difference 
match_check <- ca_check$dataframe %>%
  mutate(total_wood_match = as.integer(near(total_wood_kg, total_wood_fia, tol = 1e-2)),
         total_bark_match = as.integer(near(total_bark_kg, total_bark_fia, tol = 1e-2)),
         total_branch_match = as.integer(near(total_branch_kg, total_branch_fia, tol = 1e-2)),
         merch_wood_match = as.integer(near(merch_wood_kg, merch_wood_fia, tol = 1e-2)),
         merch_bark_match = as.integer(near(merch_bark_kg, merch_bark_fia, tol = 1e-2)),
         stump_wood_match = as.integer(near(stump_wood_kg, stump_wood_fia, tol = 1e-2)),
         stump_bark_match = as.integer(near(stump_bark_kg, stump_bark_fia, tol = 1e-2)),
         foliage_match = as.integer(near(foliage_kg, foliage_fia, tol = 1e-2))) %>%
  select(province, plot, status, decay_class, species, dbh_cm, top,
         total_wood_kg, total_wood_fia, total_wood_match,
         total_bark_kg, total_bark_fia, total_bark_match,
         total_branch_kg, total_branch_fia, total_branch_match,
         merch_wood_kg, merch_wood_fia, merch_wood_match,
         merch_bark_kg, merch_bark_fia, merch_bark_match,
         stump_wood_kg, stump_wood_fia, stump_wood_match,
         stump_bark_kg, stump_bark_fia, stump_bark_match,
         foliage_kg, foliage_fia, foliage_match)

head(match_check)
```

```{r}
match_summary <- match_check %>%
  summarize(total_n = n(),
            merch_stump_n = sum(!is.na(merch_wood_match)),
            total_wood = (sum(total_wood_match)/n())*100,
            total_bark = (sum(total_bark_match)/n())*100,
            total_branch = (sum(total_branch_match)/n())*100,
            foliage = (sum(foliage_match)/n())*100,
            # no merch or stump calculated for trees with dbh < 12.5 cm (5 in) in either BFA or FIA
            merch_wood = (sum(merch_wood_match, na.rm=TRUE)/sum(!is.na(merch_wood_match)))*100,
            merch_bark = (sum(merch_bark_match, na.rm=TRUE)/sum(!is.na(merch_bark_match)))*100,
            stump_wood = (sum(stump_wood_match, na.rm=TRUE)/sum(!is.na(stump_wood_match)))*100,
            stump_bark = (sum(stump_bark_match, na.rm=TRUE)/sum(!is.na(stump_bark_match)))*100)

match_summary
```

```{r}
checks <- function(var_name) {

  plot_df <- match_check %>%
    filter(.data[[var_name]] == 0) %>%
    group_by(plot) %>%
    summarize(n = n())
  
  sp_df <- match_check %>%
    mutate(match = case_when(.data[[var_name]] > 0.5 ~ "no_error_n",
                             .data[[var_name]]< 0.5 ~ "error_n")) %>%
    group_by(species, match) %>%
    count() %>%
    ungroup() %>%
    pivot_wider(names_from = match, values_from = n, values_fill = 0) %>%
    mutate(total_n = error_n + no_error_n,
           percent_in_pop = (total_n/sum(total_n))*100,
           percent_w_error = (error_n/total_n)*100) %>%
    filter(error_n > 0)
    
  return(list(plot_df, sp_df))
  
}
```

```{r}
checks("total_wood_match")
```

```{r}
checks("total_bark_match")
```

```{r}
checks("total_branch_match")
```

```{r}
checks("merch_wood_match")
```

```{r}
checks("merch_bark_match")
```

```{r}
checks("stump_wood_match")
```

```{r}
checks("stump_bark_match")
```

```{r}
checks("foliage_match")
```

