
```{r}
library(tidyverse)
library(BerkeleyForestsAnalytics)
library(stringr)
library(DBI)
library(RSQLite)
library(R.utils)
library(readr)
options(scipen = 999)
```

```{r}
con <- dbConnect(SQLite(), "SQLite_FIADB_ENTIRE.db")

cond_query <- "
SELECT STATECD, UNITCD, COUNTYCD, PLOT,
       INVYR, CONDID, STDORGCD
FROM COND
WHERE INVYR = 2021
  AND STATECD IN (
    1,2,4,5,6,8,9,10,12,13,
    16,17,18,19,20,21,22,23,24,25,
    26,27,28,29,30,31,32,33,34,35,
    36,37,38,39,40,41,42,44,45,46,
    47,48,49,50,51,53,54,55,56
  )
"

cond_2021_pull <- dbGetQuery(con, cond_query)
```

```{r}
cond <- cond_2021_pull %>%
  mutate(STATECD = as.character(STATECD),
         UNITCD = as.character(UNITCD),
         COUNTYCD = as.character(COUNTYCD),
         PLOT = as.character(PLOT),
         INVYR = as.character(INVYR),
         CONDID = as.character(CONDID),
         stand_org = as.character(STDORGCD)) %>%
  select(STATECD, UNITCD, COUNTYCD, PLOT, INVYR, CONDID, stand_org)

head(cond)
rm(cond_2021_pull)
```



```{r}
plot_query <- "
SELECT STATECD, UNITCD, COUNTYCD, PLOT, INVYR, ECOSUBCD
FROM PLOTGEOM
WHERE STATECD IN (
    1,2,4,5,6,8,9,10,12,13,
    16,17,18,19,20,21,22,23,24,25,
    26,27,28,29,30,31,32,33,34,35,
    36,37,38,39,40,41,42,44,45,46,
    47,48,49,50,51,53,54,55,56
  )
"

plot_2021_pull <- dbGetQuery(con, plot_query)
```

```{r}
plotgeom <- plot_2021_pull %>%
  mutate(STATECD = as.character(STATECD),
         UNITCD = as.character(UNITCD),
         COUNTYCD = as.character(COUNTYCD),
         PLOT = as.character(PLOT),
         INVYR = as.integer(INVYR)) %>%
  filter(!is.na(ECOSUBCD)) %>%
  group_by(STATECD, UNITCD, COUNTYCD, PLOT) %>%
  slice_max(INVYR, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(province = str_extract(ECOSUBCD, "^[A-Za-z]?\\d{3}"),
         letter = str_extract(province, "^[A-Za-z]"),
         number = as.numeric(str_extract(province, "\\d{3}")),
         rounded_number = floor(number/10)*10,
         division = paste0(coalesce(letter, ""), rounded_number)) %>%
  select(STATECD, UNITCD, COUNTYCD, PLOT, division, province)

head(plotgeom)
rm(plot_2021_pull)
```



```{r}
tree_query <- "
SELECT STATECD, UNITCD, COUNTYCD, PLOT,
       INVYR, CONDID, TREE, STATUSCD, DECAYCD,
       SPCD, DIA, HT, ACTUALHT, CR, CULL,
       DRYBIO_STEM, DRYBIO_STEM_BARK, DRYBIO_BRANCH,
       DRYBIO_BOLE, DRYBIO_BOLE_BARK, DRYBIO_STUMP,
       DRYBIO_STUMP_BARK, DRYBIO_FOLIAGE
FROM TREE
WHERE INVYR = 2021
  AND STATECD IN (
    1,2,4,5,6,8,9,10,12,13,
    16,17,18,19,20,21,22,23,24,25,
    26,27,28,29,30,31,32,33,34,35,
    36,37,38,39,40,41,42,44,45,46,
    47,48,49,50,51,53,54,55,56
  )
"

tree_2021_pull <- dbGetQuery(con, tree_query)
```

```{r}
tree <- tree_2021_pull %>%
  filter(INVYR == 2021,
         STATUSCD == 1 | STATUSCD == 2) %>%
  mutate(STATECD = as.character(STATECD),
         UNITCD = as.character(UNITCD),
         COUNTYCD = as.character(COUNTYCD),
         PLOT = as.character(PLOT),
         INVYR = as.character(INVYR),
         CONDID = as.character(CONDID),
         tree_id = as.character(TREE),
         site = as.character(STATECD),
         plot = as.character(PLOT),
         exp_factor = 50, # doesn't matter for tree-level comparisons 
         status = as.character(STATUSCD),
         decay_class = as.character(DECAYCD),
         species = as.character(SPCD),
         dbh = DIA,
         ht1 = HT,
         ht2 = ACTUALHT,
         crown_ratio = CR/100,
         top = if_else(HT > ACTUALHT, "N", "Y"),
         cull = if_else(is.na(CULL), 0, CULL),
         total_wood_fia = DRYBIO_STEM*0.45359, # for tons use 0.0005
         total_bark_fia = DRYBIO_STEM_BARK*0.45359,
         total_branch_fia = DRYBIO_BRANCH*0.45359,
         merch_wood_fia = DRYBIO_BOLE*0.45359,
         merch_bark_fia = DRYBIO_BOLE_BARK*0.45359,
         stump_wood_fia = DRYBIO_STUMP*0.45359,
         stump_bark_fia = DRYBIO_STUMP_BARK*0.45359,
         foliage_fia = DRYBIO_FOLIAGE*0.45359) %>%
  select(STATECD, UNITCD, COUNTYCD, PLOT, INVYR, CONDID,
         tree_id, site, plot, exp_factor, status, decay_class, species, 
         dbh, ht1, ht2, crown_ratio, top, cull,
         total_wood_fia, total_bark_fia, total_branch_fia,
         merch_wood_fia, merch_bark_fia,
         stump_wood_fia, stump_bark_fia, foliage_fia) %>%
  drop_na(status, species, dbh, ht1, ht2, crown_ratio, total_wood_fia, total_bark_fia, total_branch_fia, foliage_fia) %>%
  filter(!(status == "2" & is.na(decay_class)))

head(tree)
dim(tree)
rm(tree_2021_pull)
```



```{r}
bfa_data <- left_join(tree, cond, by = c("STATECD","UNITCD","COUNTYCD","PLOT","INVYR","CONDID")) %>%
  #mutate(stand_org = if_else(is.na(stand_org),"0", stand_org)) %>%
  left_join(plotgeom, by = c("STATECD","UNITCD","COUNTYCD","PLOT")) %>%
  select(-c(STATECD, UNITCD, COUNTYCD, PLOT, INVYR, CONDID)) %>%
  select(tree_id, division, province, site, plot, stand_org, everything())

head(bfa_data)
dim(bfa_data)
```

```{r}
all_states <- as.character(c(1,2,4,5,6,8,9,10,12,13,16,17,
                             18,19,20,21,22,23,24,25,26,27,
                             28,29,30,31,32,33,34,35,36,37,
                             38,39,40,41,42,44,45,46,47,48,
                             49,50,51,53,54,55,56))

for (state in all_states) {
  
  state_check <- tryCatch(
    
    withTimeout({
      
      state_data <- bfa_data %>% 
        filter(site == state)
      
      BiomassNSVB(data = state_data,
                  results = "by_tree",
                  input_units = "imperial",
                  output_units = "metric")
      
    }, timeout = 10*60, onTimeout = "error"),
    
    error = function(e) NULL
    
  )
  
  if (is.null(state_check)) {
    message("Skipped state: ", state)
    next
  }
  
  write_csv(state_check$dataframe, paste0("state_data_v2/output_", state, ".csv"))
}
```





```{r}
state_49_data <- bfa_data %>% filter(site == "49")
#state_49_data <- state_49_data[-c(1422, 1429, 1432, 1659, 1661, 1697, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1754, 1757, 1758, 1760, 1761, 1762, 1780, 1785, 1786, 1787, 1788, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1868, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2102),]

state_49_check <- BiomassNSVB(data = state_49_data,
                              results = "by_tree",
                              input_units = "imperial",
                              output_units = "metric")

#write_csv(state_49_check$dataframe, paste0("state_data/output_49.csv"))
```

```{r}
state_49_data <- bfa_data %>% filter(site == "49")
state_49_data[c(1422, 1429, 1432, 1659, 1661, 1697, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1754, 1757, 1758, 1760, 1761, 1762, 1780, 1785, 1786, 1787, 1788, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1868, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2102),]

state_49_data %>% filter(species == "122", division == "M340")
```

```{r}
state_49_bad <- bfa_data %>% filter(site == "49")
state_49_bad <- state_49_bad[c(1422, 1429, 1432, 1659, 1661, 1697, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1754, 1757, 1758, 1760, 1761, 1762, 1780, 1785, 1786, 1787, 1788, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1868, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2102),]

state_49_check_bad <- BiomassNSVB(data = state_49_bad,
                              results = "by_tree",
                              input_units = "imperial",
                              output_units = "metric")
```


```{r}
state_32_data <- bfa_data %>% filter(site == "36")
#state_32_data <- state_32_data[-c(61, 63),]

state_32_check <- BiomassNSVB(data = state_32_data,
                              results = "by_tree",
                              input_units = "imperial",
                              output_units = "metric")

#write_csv(state_32_check$dataframe, paste0("state_data_v2/output_36.csv"))
```

```{r}
state_32_data <- bfa_data %>% filter(site == "32")
state_32_data[c(61, 63),]

state_32_data %>% filter(species == "122", division == "M340")
```





```{r}
state_files <- list.files("state_data_v2", pattern = "\\.csv$", full.names = TRUE)

all_check <- state_files %>%
  lapply(read_csv, col_types = cols(division = col_character(),
                                    province = col_character())) %>%
  bind_rows()
```

```{r}
match_check <- all_check %>%
  # use 10g (0.01 kg) difference 
  mutate(total_wood_match = as.integer(near(total_wood_kg, total_wood_fia, tol = 1e-2)),
         total_bark_match = as.integer(near(total_bark_kg, total_bark_fia, tol = 1e-2)),
         total_branch_match = as.integer(near(total_branch_kg, total_branch_fia, tol = 1e-2)),
         merch_wood_match = as.integer(near(merch_wood_kg, merch_wood_fia, tol = 1e-2)),
         merch_bark_match = as.integer(near(merch_bark_kg, merch_bark_fia, tol = 1e-2)),
         stump_wood_match = as.integer(near(stump_wood_kg, stump_wood_fia, tol = 1e-2)),
         stump_bark_match = as.integer(near(stump_bark_kg, stump_bark_fia, tol = 1e-2)),
         foliage_match = as.integer(near(foliage_kg, foliage_fia, tol = 1e-3))) %>% # use 1g (0.001 kg) difference 
  select(province, plot, tree_id, status, decay_class, species, dbh_cm, top, ht1_m, ht2_m, crown_ratio, cull,
         total_wood_kg, total_wood_fia, total_wood_match,
         total_bark_kg, total_bark_fia, total_bark_match,
         total_branch_kg, total_branch_fia, total_branch_match,
         merch_wood_kg, merch_wood_fia, merch_wood_match,
         merch_bark_kg, merch_bark_fia, merch_bark_match,
         stump_wood_kg, stump_wood_fia, stump_wood_match,
         stump_bark_kg, stump_bark_fia, stump_bark_match,
         foliage_kg, foliage_fia, foliage_match)

head(match_check)
```

```{r}
match_summary <- match_check %>%
  summarize(total_n = n(),
            merch_stump_n = sum(!is.na(merch_wood_match)),
            total_wood = (sum(total_wood_match)/n())*100,
            total_bark = (sum(total_bark_match)/n())*100,
            total_branch = (sum(total_branch_match)/n())*100,
            foliage = (sum(foliage_match)/n())*100,
            # no merch or stump calculated for trees with dbh < 12.5 cm (5 in) in either BFA or FIA
            merch_wood = (sum(merch_wood_match, na.rm=TRUE)/sum(!is.na(merch_wood_match)))*100,
            merch_bark = (sum(merch_bark_match, na.rm=TRUE)/sum(!is.na(merch_bark_match)))*100,
            stump_wood = (sum(stump_wood_match, na.rm=TRUE)/sum(!is.na(stump_wood_match)))*100,
            stump_bark = (sum(stump_bark_match, na.rm=TRUE)/sum(!is.na(stump_bark_match)))*100)

match_summary
```
